import type { FormConfig } from '@/types/form';

export const formConfig: FormConfig = {
  title: 'Cadastro de Usuário',
  description: 'Formulário gerado dinamicamente a partir de uma estrutura JSON.',
  fields: [
    {
      id: 'name',
      label: 'Nome completo',
      type: 'text',
      required: true,
      placeholder: 'Digite seu nome',
      minLength: 3,
    },
    {
      id: 'email',
      label: 'E-mail',
      type: 'email',
      required: true,
      placeholder: 'voce@email.com',
    },
    {
      id: 'password',
      label: 'Senha',
      type: 'password',
      required: true,
      placeholder: 'Mínimo de 6 caracteres',
      minLength: 6,
    },
    {
      id: 'age',
      label: 'Idade',
      type: 'number',
      required: true,
      placeholder: 'Sua idade',
      min: 0,
      max: 120,
    },
    {
      id: 'bio',
      label: 'Sobre você',
      type: 'textarea',
      required: false,
      placeholder: 'Conte um pouco sobre você...',
      maxLength: 280,
      helperText: 'Até 280 caracteres.',
    },
    {
      id: 'gender',
      label: 'Gênero',
      type: 'radio',
      required: true,
      options: [
        { label: 'Masculino', value: 'male' },
        { label: 'Feminino', value: 'female' },
        { label: 'Outro', value: 'other' },
      ],
    },
    {
      id: 'state',
      label: 'Estado',
      type: 'select',
      required: true,
      placeholder: 'Selecione um estado',
      options: [
        { label: 'São Paulo', value: 'SP' },
        { label: 'Rio de Janeiro', value: 'RJ' },
        { label: 'Minas Gerais', value: 'MG' },
        { label: 'Paraná', value: 'PR' },
        { label: 'Rio Grande do Sul', value: 'RS' },
        { label: 'Bahia', value: 'BA' },
      ],
    },
    {
      id: 'birthDate',
      label: 'Data de nascimento',
      type: 'date',
      required: true,
      placeholder: 'DD/MM/AAAA',
    },
    {
      id: 'newsletter',
      label: 'Quero receber novidades por e-mail',
      type: 'checkbox',
      required: false,
    },
    {
      id: 'notifications',
      label: 'Ativar notificações push',
      type: 'switch',
      required: false,
    },
  ],
};
